### ISSUE TITLE
FAILED: /android/SyberiaPie/out/soong/.intermediates/frameworks/native/services/surfaceflinger/libsurfaceflinger/android_arm64_armv8-a_cortex-a53_core_shared/libsurfaceflinger.so.toc

### ISSUE THREAD

**Issue by kaushalsitapara** [syberia-project/platform_frameworks_native#2]
[ 83% 28437/34219] //frameworks/native/services/surfaceflinger:libsurfaceflinger generate toc libsurfaceflinger.so
FAILED: /android/SyberiaPie/out/soong/.intermediates/frameworks/native/services/surfaceflinger/libsurfaceflinger/android_arm64_armv8-a_cortex-a53_core_shared/libsurfaceflinger.so.toc 
echo "module libsurfaceflinger missing dependencies: display_intf_headers, libqdMetaData.system" && false
module libsurfaceflinger missing dependencies: display_intf_headers, libqdMetaData.system
[ 83% 28438/34219] //frameworks/native/services/surfaceflinger:libsurfaceflinger link libsurfaceflinger.so
FAILED: /android/SyberiaPie/out/soong/.intermediates/frameworks/native/services/surfaceflinger/libsurfaceflinger/android_arm64_armv8-a_cortex-a53_core_shared/libsurfaceflinger.so 
echo "module libsurfaceflinger missing dependencies: display_intf_headers, libqdMetaData.system" && false
module libsurfaceflinger missing dependencies: display_intf_headers, libqdMetaData.system
[ 83% 28439/34219] //frameworks/native/services/surfaceflinger:libsurfaceflinger link libsurfaceflinger.so [arm]
FAILED: /android/SyberiaPie/out/soong/.intermediates/frameworks/native/services/surfaceflinger/libsurfaceflinger/android_arm_armv8-a_cortex-a53.a57_core_shared/libsurfaceflinger.so 
echo "module libsurfaceflinger missing dependencies: display_intf_headers, libqdMetaData.system" && false
module libsurfaceflinger missing dependencies: display_intf_headers, libqdMetaData.system
[ 83% 28444/34219] //system/core/storaged:libstoraged static link libstoraged.a
ninja: build stopped: subcommand failed.
01:28:33 ninja failed with: exit status 1
build/make/core/main.mk:21: recipe for target 'run_soong_ui' failed
make: *** [run_soong_ui] Error 1

**Comment by kaushalsitapara** [comment]
not fixed but came to know that you have to make some changes to your tree because it's surfaceflinger is based on caf.

**Comment by eymenyg** [comment]
> 
> 
> fixed by myself

Can you tell how?

**Comment by kaushalsitapara** [comment]
> > fixed by myself
> 
> Can you tell how?

i don't know how to fix that.

**Comment by thinhx2** [comment]
I have this problem

**Comment by Mikdadali** [comment]
how to solve this?

**Comment by Mikdadali** [comment]
i have this error

![Screenshot_20200414-231912](https://user-images.githubusercontent.com/10883393/79256911-6907a100-7ea6-11ea-8551-6fa3dca6bfb2.jpg)

**Comment by kaushalsitapara** [comment]
https://github.com/sagarrokade006/platform_frameworks_native/commits/10.0 follow commit made on 15 arpil 2020 it will get fixed.

**Comment by jiwangbo** [comment]
I encountered the same mistake, what is the reason，Specifically:
FAILED: out/soong/.intermediates/system/bt/Android_test/libmesh_service/android_arm64_armv8-a_core_static/libmesh_service.a
echo "module libmesh_service missing dependencies: heartbeat/include" && false
module libmesh_service missing dependencies: heartbeat/include
